// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID                int64     `json:"id"`
	Email             string    `json:"email"`
	EncryptedPassword string    `json:"encrypted_password"`
	CreatedAt         time.Time `json:"created_at"`
}

type Post struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	// 포스트는 비어 있을 수 없습니다.
	Body        string       `json:"body"`
	OwnerID     int64        `json:"owner_id"`
	CreatedAt   time.Time    `json:"created_at"`
	PublishedAt sql.NullTime `json:"published_at"`
}

type Relationship struct {
	FollowerID int64     `json:"follower_id"`
	FollowedID int64     `json:"followed_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Response struct {
	ID int64 `json:"id"`
	// 답변은 반드시 내용이 있어야 합니다.
	Body      string    `json:"body"`
	PostID    int64     `json:"post_id"`
	OwnerID   int64     `json:"owner_id"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID int64 `json:"id"`
	// 이메일은 필수 항목입니다.
	Email string `json:"email"`
	// 사용자명은 필수 항목입니다.
	Username          string    `json:"username"`
	EncryptedPassword string    `json:"encrypted_password"`
	CreatedAt         time.Time `json:"created_at"`
}
